version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: cafeteria_db_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password_root
      POSTGRES_DB: cafeteria_db
    volumes:
      # Esto busca la carpeta db que creamos antes
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: cafeteria_app_container
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://app_user:secreto123@db:5432/cafeteria_db
    depends_on:
      - db
